title: The Haskell Cast
baseurl: /
url: http://www.haskellcast.com

author:
  name: The Haskell Cast
  url: /

description: Listen to regular interviews with the Haskell community. The podcast covers news, libraries, and whatever other topics we wander onto with our guests.
keywords:
- Haskell
- Programming
- Podcast
- Interview
- Functional

podcast:
  owner:
    name: The Haskell Cast
    email: haskellcast@haskellcast.com
  explicit: "no"
  image: http://www.haskellcast.com/img/haskellcast-logo.jpg
  category: Technology
  subcategory: Tech News
  subtitle: Interviews and Insights from the Haskell Community
  defaultFileType: audio/mpeg
  year: 2013

gems: [jekyll-paginate]

paginate: 20

source: .
destination: ./_site

future: false
permalink: /episode/:title

exclude:
- README.markdown

disqus:
  shortname: haskellcast

defaults:
- scope:
    path: ""
  values:
    hosts:
    - name: Chris Forno
      twitter: jekor
      gravatar: 4f4283e61ace51643f3e1b9295dfe7c4
    - name: Alp Mestanogullari
      twitter: alpmestan
      gravatar: 11ba6dfa8271fb1cd0c475a2c0626853
